-- START SQL STATEMENTS DATE --> 12/08/2024
ALTER TABLE IF EXISTS INGREDIENT ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS ALLERGENIC ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_INGREDIENT ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_ALLERGENIC ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_ELABORATION_STEP ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_RECIPE_ELABORATION_STEP ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER_FITNESS_DATA ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER_SALUHUD_USER_FITNESS_DATA ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SLEEP_HISTORICAL ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SLEEP_HISTORICAL_ENTRY ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS DAILY_STEPS_HISTORICAL ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS DAILY_STEPS_HISTORICAL_ENTRY ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS WEIGHT_HISTORICAL ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS WEIGHT_HISTORICAL_ENTRY ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
-- END SQL STATEMENTS DATE --> 12/08/2024

-- START SQL STATEMENTS DATE --> 15/08/2024
ALTER TABLE IF EXISTS SALUHUD_USER ADD COLUMN IF NOT EXISTS NAME TEXT NOT NULL;
ALTER TABLE IF EXISTS SALUHUD_USER ADD COLUMN IF NOT EXISTS SURNAME TEXT;
ALTER TABLE IF EXISTS SALUHUD_USER ADD COLUMN IF NOT EXISTS PHONE_NUMBER TEXT UNIQUE;
-- END SQL STATEMENTS DATE --> 15/08/2024

-- START SQL STATEMENTS DATE --> 03/10/2024
ALTER TABLE IF EXISTS SLEEP_HISTORICAL_ENTRY ALTER COLUMN SLEEP_EVALUATION TYPE VARCHAR(255);
ALTER TABLE IF EXISTS DAILY_STEPS_HISTORICAL_ENTRY ALTER COLUMN steps_evaluation TYPE VARCHAR(255);
-- END SQL STATEMENTS DATE --> 03/10/2024
