-- START SQL STATEMENTS DATE --> 12/08/2024
ALTER TABLE IF EXISTS INGREDIENT ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS ALLERGENIC ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_INGREDIENT ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_ALLERGENIC ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_ELABORATION_STEP ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS RECIPE_RECIPE_ELABORATION_STEP ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS FORUM ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS FORUM_THREAD ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS FORUM_MESSAGE ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER_FITNESS_DATA ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER_PERSONAL_DATA ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER_PERSONAL_DATA_SALUHUD_USER ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SALUHUD_USER_SALUHUD_USER_FITNESS_DATA ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SLEEP_HISTORICAL ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS SLEEP_HISTORICAL_ENTRY ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS DAILY_STEPS_HISTORICAL ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS DAILY_STEPS_HISTORICAL_ENTRY ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS WEIGHT_HISTORICAL ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
ALTER TABLE IF EXISTS WEIGHT_HISTORICAL_ENTRY ADD COLUMN IF NOT EXISTS ENTITY_VERSION BIGINT;
-- END SQL STATEMENTS DATE --> 12/08/2024
