GRANT SELECT, INSERT, UPDATE, DELETE ON INGREDIENT TO saluhud_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECIPE TO saluhud_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALLERGENIC TO saluhud_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON INGREDIENT_ALLERGENIC TO saluhud_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECIPE_INGREDIENT TO saluhud_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECIPE_ALLERGENIC TO saluhud_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON RECIPE_ELABORATION_STEP TO saluhud_admin;